name: Android Pull Request & Master CI

on:
  pull_request:
    branches:
      - 'master'

jobs:
  test:
    name: Run Unit Tests
    runs-on: ubuntu-18.04

    steps:
      - name: Android Github Action
        uses: Vukan-Markovic/Github-Android-Action@1.2
