name: CI

on:
  pull_request:
    branches:
      - 'master'
  push:
    branches:
      - 'master'

jobs:
   build:
     name: Run Unit Tests
     runs-on: ubuntu-latest
     
     steps:
      - uses: actions/checkout@v1
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Unit tests
        run: bash ./gradlew test --stacktrace
        
      - name: Android Github Action
        uses: Vukan-Markovic/Github-Android-Action@1.2
